### ISSUE TITLE
com崩了吗

### ISSUE THREAD

**Issue by molezz** [oxyry/qireader#37]
cn好像没问题
2天了  clear local 没效果
Oops! Something went wrong.
Network error

```
URL: https://www.qireader.com/
TypeError: Failed to fetch
TypeError: Failed to fetch
    at chrome-extension://odphnbhiddhdpoccbialllejaajemdio/scripts/inspector.js:7:1965
    at new Promise (<anonymous>)
    at window.fetch (chrome-extension://odphnbhiddhdpoccbialllejaajemdio/scripts/inspector.js:7:1923)
    at gt (https://www.qireader.com/assets/index-978d34b1.js:315:24137)
    at z5 (https://www.qireader.com/assets/index-978d34b1.js:315:41131)
    at async L5 (https://www.qireader.com/assets/index-978d34b1.js:315:38975)
```

**Comment by weijarz** [comment]
最近因为.com原先套的cloudflare不是太稳，就切到了DigitalOcean的服务器上。
.cn线路目前用的是香港的服务器，相对.com的未优化线路应该更快。

看流量统计似乎切换过后并没有变化，应该对绝大部分国内用户来说.com也是可以连接上的，你这边是什么宽带？

**Comment by molezz** [comment]
> 最近因为.com原先套的cloudflare不是太稳，就切到了DigitalOcean的服务器上。 .cn线路目前用的是香港的服务器，相对.com的未优化线路应该更快。
> 
> 看流量统计似乎切换过后并没有变化，应该对绝大部分国内用户来说.com也是可以连接上的，你这边是什么宽带？
哦， 这样， 试了下各种， 移动宽带和移动4g都不行， 电信宽带（企业）正常

**Comment by weijarz** [comment]
不知道是移动的问题还是ipv6的问题，按理说我只配置了ipv4的dns应该只连接ipv4的。
我现在把 .com 换了个机房了，如果你那边移动能打开应该就是DigitalOcean机房的问题。

**Comment by molezz** [comment]
嗯  ok了  同时也再清了下整个浏览器缓存
